// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolJournal.Api.Data;

#nullable disable

namespace SchoolJournal_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("SchoolJournal.Api.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subject_id");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            SubjectId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5,
                            SubjectId = 4,
                            Value = 3
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 8,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 8,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 8,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 8,
                            SubjectId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 9,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 9,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 9,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 9,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 9,
                            SubjectId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 10,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 10,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 10,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 10,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 10,
                            SubjectId = 4,
                            Value = 3
                        });
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("teacher_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "5А",
                            TeacherName = "Иванова Мария Петровна"
                        },
                        new
                        {
                            Id = 2,
                            Name = "5Б",
                            TeacherName = "Петров Сергей Иванович"
                        },
                        new
                        {
                            Id = 3,
                            Name = "9А",
                            TeacherName = "Сидорова Анна Викторовна"
                        });
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            FullName = "Алексеев Иван"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            FullName = "Борисова Анна"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            FullName = "Власов Пётр"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            FullName = "Громова Ольга"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            FullName = "Дмитриев Никита"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            FullName = "Егорова Светлана"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 3,
                            FullName = "Жуков Артём"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 3,
                            FullName = "Захарова Дарья"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 3,
                            FullName = "Иванов Максим"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 3,
                            FullName = "Кузнецова Полина"
                        });
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Русский язык"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "История"
                        });
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.Grade", b =>
                {
                    b.HasOne("SchoolJournal.Api.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolJournal.Api.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.Student", b =>
                {
                    b.HasOne("SchoolJournal.Api.Models.SchoolClass", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.SchoolClass", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("SchoolJournal.Api.Models.Subject", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
